/*
TASK 01: Solution

Write a SQL query to retrieve all the customer information 
along with the total number of orders placed by each customer. 
Display the result in descending order of the number of orders.
*/


SELECT customers.name, customers.email, customers.location, count(*) as total_orders 
FROM orders 

JOIN customers ON orders.customer_id = customers.id 

GROUP BY orders.customer_id

ORDER BY total_orders DESC;


/*
TASK 02: Solution

Write a SQL query to retrieve the 

product name, 
quantity, and 
total amount for each order item.
 
Display the result in ascending order of the order ID.
*/
SELECT order_items.order_id, products.name, order_items.quantity, order_items.unit_price, ( order_items.unit_price * order_items.quantity ) as total_amount
FROM order_items 

JOIN products ON order_items.product_id = products.id 

ORDER BY order_items.order_id ASC;





/*
TASK 03: Solution

Write a SQL query to retrieve the 
total revenue generated by each product category. 

Display the category name along with the total revenue in descending order of the revenue.
*/

SELECT categories.name, SUM(order_items.total_amount) as total_revenue
FROM order_items 

JOIN products ON order_items.product_id = products.id 
JOIN categories ON products.category_id = categories.id 

GROUP BY products.category_id

ORDER BY total_revenue DESC;



/*
TASK 04: Solution

Write a SQL query to retrieve the top 5 customers who have made the highest total purchase amount. 
Display the customer name along with the total purchase amount in descending order of the purchase amount.
*/


SELECT customers.name, SUM(orders.total_amount) as total_purchase_amount
FROM orders 


JOIN customers ON orders.customer_id = customers.id 

GROUP BY orders.customer_id

ORDER BY total_purchase_amount DESC

LIMIT 5;

